dist: bionic
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
    update: true
sudo: required

# DOCKER_USER and DOCKER_PASS is set in travis
env:
  global:
    - IMAGE=drpsychick/influxdb
    - PLATFORMS=linux/amd64
    - DOCKER_CLI_EXPERIMENTAL=enabled
  matrix:
    - ALPINE_VERSION=alpine
    - ALPINE_VERSION=1.7.3-alpine
    - ALPINE_VERSION=1.6.5-alpine
    - ALPINE_VERSION=1.5.4-alpine

before_script:
  # upgrade to latest docker-ce from repo
  - sudo apt-get -y install docker-ce
  # enable experimental in docker daemon
  - docker_conf=$(sudo cat /etc/docker/daemon.json |jq '. + {"experimental":"enabled"}')
  - echo "$docker_conf" | sudo tee /etc/docker/daemon.json
  - sudo service docker start
  - docker version
  - docker buildx version
  # build the image for all platforms
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
  - docker buildx inspect --bootstrap
  - docker buildx build --progress plain --platform $PLATFORMS --build-arg UBUNTU_VERSION=$UBUNTU_VERSION -t $IMAGE .
  # load a single image for local tests, see https://github.com/docker/buildx/issues/59
  - docker buildx build --progress plain --platform linux/amd64 -t $IMAGE --load .
  - export VERSION=$(docker run --rm $IMAGE influxd version |awk '$1 == "InfluxDB" { print $2; exit }' |tr -d 'v')

script:
  # test always passes
  - echo "Alpine $ALPINE_VERSION influxd $VERSION"
  - >
    echo "Running tests...";
    docker run --rm $IMAGE influxd version

# push images to docker hub
after_success:
  - bash deploy.sh
