# Required variables
# REPO, IMAGE_NAME
# DOCKER_USER, DOCKER_PASS
version: 2.1
aliases:
  - &parameters
      platforms:
        default: linux/amd64,linux/arm64
        type: string
      influxdb_version:
        default: alpine
        type: string
  - &docker
      - image: drpsychick/dind-buildx:latest
  - &steps
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Prepare docker buildx
          command: |
            docker version
            docker buildx version
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create xbuilder
            docker buildx create xbuilder --name xbuilder --use
            docker buildx inspect --bootstrap
      - run:
          name: Test default.env
          command: |
            docker buildx build --progress plain --platform linux/amd64 \
              --build-arg INFLUXDB_VERSION=<< parameters.influxdb_version >> \
              --tag $REPO/$IMAGE_NAME:test --load .
            docker run --rm -it $REPO/$IMAGE_NAME:test influxd version
            docker run --rm -it --env-file test.env $REPO/$IMAGE_NAME:test --test
      - run:
          name: Build and push all platforms
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin &> /dev/null || exit 1
              export TAG=<< parameters.influxdb_version >>
              docker buildx build --progress plain --platform << parameters.platforms >> \
                --build-arg INFLUXDB_VERSION=<< parameters.influxdb_version >> \
                --tag $REPO/$IMAGE_NAME:$TAG --push .
              
              if [ "$TAG" = "1.8" ]; then
                export TAG=latest
                docker buildx build --progress plain --platform << parameters.platforms >> \
                --build-arg INFLUXDB_VERSION=<< parameters.influxdb_version >> \
                --tag $REPO/$IMAGE_NAME:$TAG --push .
              fi
            fi
jobs:
  build:
    parameters: *parameters
    docker: *docker
    steps: *steps

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          # mondays, 6:03 am, UTC
          cron: "3 6 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          matrix:
            parameters:
              platforms: ["linux/amd64,linux/arm64"]
              influxdb_version: ["1.8", "1.7"]
  build:
    jobs:
      - build:
          matrix:
            parameters:
              platforms: ["linux/amd64,linux/arm64"]
              influxdb_version: ["1.8", "1.7"]
