# Required variables
# REPO, IMAGE_NAME
# PLATFORMS
# DOCKER_USER, DOCKER_PASS
version: 2.1
aliases:
  - &docker
      - image: docker:git
  - &steps
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare docker buildx
          command: |
            apk add --no-cache jq openrc docker
            mkdir -p /etc/docker
            docker_conf=$( (cat /etc/docker/daemon.json 2>/dev/null || echo "{}") |jq '. + {"experimental":"enabled"}')
            echo "$docker_conf" | tee /etc/docker/daemon.json
            service docker status
            sleep 10
      - run:
          name: Prep docker
          command: |
            docker version
            docker buildx version
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --name xbuilder --use
            docker buildx inspect --bootstrap
      - run:
          name: Build all platforms
          command: |
            docker buildx build --progress plain --platform $PLATFORMS --build-arg INLFUXDB_VERSION=$INFLUXDB_VERSION -t $REPO/$IMAGE_NAME:$INFLUXDB_VERSION .
      - run:
          name: Build and push all platforms
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin &> /dev/null || exit 1
              docker buildx build --progress plain --platform $PLATFORMS --build-arg INLFUXDB_VERSION=$INFLUXDB_VERSION -t $REPO/$IMAGE_NAME:$INFLUXDB_VERSION --push .
            fi
jobs:
  build_alpine:
    environment:
      INFLUXDB_VERSION: alpine
    docker: *docker
    steps: *steps
  build_18-alpine:
    environment:
      INFLUXDB_VERSION: 1.8-alpine
    docker: *docker
    steps: *steps
  build_17-alpine:
    environment:
      INFLUXDB_VERSION: 1.7-alpine
    docker: *docker
    steps: *steps
  build_16-alpine:
    environment:
      INFLUXDB_VERSION: 1.6-alpine
    docker: *docker
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - build_16-alpine
      - build_17-alpine
      - build_18-alpine
      - build_alpine