# Required variables
# REPO, IMAGE_NAME
# PLATFORMS
# DOCKER_USER, DOCKER_PASS

version: 2.1
orbs:
  docker-buildx: sensu/docker-buildx@1.1.1
parameters:
  version:
    default: 0.5.1
    type: string
aliases:
  - &docker
      - image: docker:dind
  - &docker-ubuntu
      - image: ubuntu:latest
  - &steps
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker buildx
          command: |
            mkdir -p ~/.docker/cli-plugins
            baseUrl="https://github.com/docker/buildx/releases/download"
            fileName="buildx-v<< parameters.version >>.linux-amd64"
            url="${baseUrl}/v<< parameters.version >>/${fileName}"
            curl -sSL -o ~/.docker/cli-plugins/docker-buildx $url
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            echo 'export DOCKER_CLI_EXPERIMENTAL="enabled"' >> $BASH_ENV
      - run:
          name: Prepare docker buildx
          command: |
            docker buildx install
            docker version
            docker buildx version
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --name xbuilder --use
            docker buildx inspect --bootstrap
      - run:
          name: Build all platforms
          command: |
            docker buildx build --progress plain --platform $PLATFORMS --build-arg INLFUXDB_VERSION=$INFLUXDB_VERSION -t $REPO/$IMAGE_NAME:$INFLUXDB_VERSION .
      - run:
          name: Build and push all platforms
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin &> /dev/null || exit 1
              docker buildx build --progress plain --platform $PLATFORMS --build-arg INLFUXDB_VERSION=$INFLUXDB_VERSION -t $REPO/$IMAGE_NAME:$INFLUXDB_VERSION --push .
            fi
jobs:
  build_alpine:
    parameters:
      version:
        default: 0.5.1
        type: string
    environment:
      INFLUXDB_VERSION: alpine
    docker: *docker-ubuntu
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install curl docker
          command: |
            export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
            apt update && apt install -y curl docker
      - docker-buildx/install
  build_18-alpine:
    parameters:
      version:
        default: 0.5.1
        type: string
    environment:
      INFLUXDB_VERSION: 1.8-alpine
    docker: *docker
    steps: *steps
  build_17-alpine:
    parameters:
      version:
        default: 0.5.1
        type: string
    environment:
      INFLUXDB_VERSION: 1.7-alpine
    docker: *docker
    steps: *steps
  build_16-alpine:
    parameters:
      version:
        default: 0.5.1
        type: string
    environment:
      INFLUXDB_VERSION: 1.6-alpine
    docker: *docker
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - build_16-alpine
      - build_17-alpine
      - build_18-alpine
      - build_alpine